cluster_name            =    "fuchicorp"
node_count              =    "2"
cpath                   =    "/root/cluster-infrastructure/kube-cluster/service_account_key.json"
project                 =    "tough-country-240119"
region                  =    "us-central1"
node_name               =    "fuchicorp"