cluster_name            =    "fuchicorp"
initial_node_count      =    "2"
cpath                   =    "/home/fuchicorp/cluster-infrastructure/kube-cluster/service_account_key.json"
project                 =    "fuchicorp-239622"
region                  =    "us-central1"